name: "Deploy NodeJS to VPS"
description: "Checks out a NodeJS repository, builds it, copies it to a remote SSH location, and optionally runs a bash script."

inputs:
  node-version:
    description: "The NodeJS version used to setup the environment and build to project."
    required: true
  ci-build-script:
    description: "The optional build script that will be run post `npm run build`."
    required: false
   
runs:
  using: "composite"
  steps:
    - name: "Exit early if required inputs are not provided."
      if: ${{ inputs.node-version == '' }}
      run: 'echo "Error: node-version must be provided." && exit 1'
      shell: "bash"
      
    - name: "Check out the current NodeJS repository"
      uses: actions/checkout@v3
      
    - name: "Setup NodeJS enironment"
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        
    - name: "Build the project"
      run: |
            npm install
            npm run build
      shell: "bash"
            
    - name: "Execute custom, optional, CI build script"
      if: ${{ inputs.ci-build-script != '' }}
      run: ${{ inputs.ci-build-script }}
      shell: "bash"

# runs:
#   using: "composite"
#   steps:
#     - name: "Debug output"
#       run: "echo \"${{ toJSON(inputs) }}\""
#       shell: "bash"
      
#     - name: "Execute custom, optional, CI build script"
#       if: ${{ inputs.ci-build-script != '' }}
#       run: ${{ inputs.ci-build-script }}
#       shell: "bash"
      
#     - name: "Execute custom #2"
#       if: ${{ inputs.ci-build-script == '' }}
#       run: "echo test null"
#       shell: "bash"
