name: "Deploy NodeJS to VPS"
description: "Checks out a NodeJS repository, builds it, copies it to a remote SSH location, and optionally runs a bash script."

inputs:
  node-version:
    description: "The NodeJS version used to setup the environment and build to project."
    required: true
  ci-build-script:
    description: "The optional build script that will be run post `npm run build`."
    required: false
  host:
    description: "The SSH host."
    required: true
  username:
    description: "The SSH username."
    required: true
  port:
    description: "The SSH port, defaults to 22."
    required: true
    default: 22
  key:
    description: "The private SSH key to use to connect to the remote droplet."
    required: true
  source:
    description: "The source directories to copy to the remote droplet, separated by commas; i.e.: ./build,./scripts"
    required: true
  target:
    description: "The target directory inside which to copy the selected source directories or files."
    required: true
  ssh-script:
    description: "The optional script to run on the remote droplet as a last step."
    required: false
   
runs:
  using: "composite"
  steps:
    - name: "Exit early if required inputs are not provided."
      if: ${{ inputs.node-version == '' }}
      run: 'echo "Error: node-version must be provided." && exit 1'
      shell: "bash"
      
    - name: "Check out the current NodeJS repository"
      uses: actions/checkout@v3
      
    - name: "Setup NodeJS enironment"
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        
    - name: "Build the project"
      run: |
            npm install
            npm run build
      shell: "bash"
            
    - name: "Execute custom, optional, CI build script"
      if: ${{ inputs.post-build-script != "" }}
      run: ${{ inputs.post-build-script }}
      shell: "bash"
      
    - name: "Copy targets to remote droplet"
      uses: appleboy/scp-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        port: ${{ inputs.port }}
        key: ${{ inputs.key }}
        source: ${{ inputs.source }}
        target: ${{ inputs.target }}
        
    - name: "Build the project and debloat"
      uses: appleboy/ssh-action@master
      if: ${{ inputs.ssh-script != "" }}
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        port: ${{ inputs.port }}
        key: ${{ inputs.key }}
        script: ${{ inputs.ssh-script }}
